name: "Mis gastos"
description: "Provides a backend for https://github.com/brunopk/mis-gastos-web"
version: "1.0.0"
slug: "misgastos"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386