{
 "title": "Mis gastos",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Category", "query": "SELECT name FROM category" },
   {
    "name": "Subcategory",
    "query": "SELECT s.name FROM subcategory s JOIN category c ON c.id = s.category_id WHERE c.name IN (${Category})"
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  SUM(value) AS 'Total'\nFROM (\n  SELECT\n    CASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n    JOIN category sc ON sc.id = s.category_id\n    WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n    GROUP BY s.id \n) s\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n\tcategory_name AS metric,\n\tSUM(s.value) AS value\nFROM (\n\tSELECT\n\t\tsc.name AS category_name,\n\t\tCASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n\tFROM spend s\n\tLEFT JOIN income i ON s.id = i.spend_id\n\tLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n\tJOIN category sc ON sc.id = s.category_id \n  WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n\tGROUP BY s.id ) s\nGROUP BY category_name\n"
    }
   ]
  },
  {
   "title": "Categories",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  category_name AS 'Category',\n  SUM(value) AS 'Total'\n FROM (\n  SELECT\n    sc.name AS category_name,\n    CASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n    JOIN category sc ON sc.id = s.category_id\n    WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n    GROUP BY s.id ) s\n GROUP BY s.category_name\n ORDER BY s.category_name ASC\n"
    }
   ]
  },
  {
   "title": "Subcategories",
   "type": "table",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  subcategory_name AS 'Subcategory',\n  SUM(value) AS 'Total'\n FROM (\n  SELECT\n    ss.name AS subcategory_name,\n    CASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n    JOIN category c ON s.category_id = c.id\n    WHERE $__timeFilter(s.date) AND c.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n    GROUP BY s.id ) s\n GROUP BY s.subcategory_name\n ORDER BY s.subcategory_name ASC\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 12 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n\tsubcategory_name AS metric,\n\tSUM(s.value) AS 'Sin definir'\nFROM (\n\tSELECT\n\t\tss.name AS subcategory_name,\n\t\tCASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n\tFROM spend s\n\tLEFT JOIN income i ON s.id = i.spend_id\n\tLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n\tJOIN category c ON c.id = s.category_id\n  WHERE $__timeFilter(s.date) AND c.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n\tGROUP BY s.id ) s\nGROUP BY metric\n"
    }
   ]
  },
  {
   "title": "Groups",
   "type": "table",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  group_name AS 'Group',\n  SUM(value) AS 'Total'\n FROM (\n  SELECT\n    sg.name AS group_name,\n    CASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n    LEFT JOIN `group` sg ON sg.id = s.group_id\n    JOIN category sc ON sc.id = s.category_id\n    WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n    GROUP BY s.id ) s\n GROUP BY group_name\n ORDER BY group_name ASC\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 24 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n\tgroup_name AS metric,\n\tSUM(s.value) AS 'Sin definir'\nFROM (\n\tSELECT\n\t\tsg.name AS group_name,\n\t\tCASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n\tFROM spend s\n\tLEFT JOIN income i ON s.id = i.spend_id\n\tLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n\tLEFT JOIN `group` sg ON sg.id = s.group_id\n\tJOIN category c ON c.id = s.category_id\n  WHERE $__timeFilter(s.date) AND c.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n\tGROUP BY s.id ) s\nGROUP BY metric\n"
    }
   ]
  },
  {
   "title": "Accounts",
   "type": "table",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  account_name AS 'Account',\n  SUM(value) AS 'Total'\n FROM (\n  SELECT\n    a.name AS account_name,\n    CASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n    LEFT JOIN `group` sg ON sg.id = s.group_id\n    JOIN category sc ON sc.id = s.category_id\n    JOIN account a ON a.id = s.account_id\n    WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n    GROUP BY s.id ) s\n GROUP BY account_name\n ORDER BY account_name ASC\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 36 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n\taccount_name AS metric,\n\tSUM(s.value) AS value\nFROM (\n\tSELECT\n\t\ta.name AS account_name,\n\t\tCASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n\tFROM spend s\n\tLEFT JOIN income i ON s.id = i.spend_id\n\tLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n\tJOIN account a ON a.id = s.account_id\n\tJOIN category c ON c.id = s.category_id\n  WHERE $__timeFilter(s.date) AND c.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n\tGROUP BY s.id ) s\nGROUP BY metric\n"
    }
   ]
  }
 ]
}