{
 "title": "Mis gastos (monthly)",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Category", "query": "SELECT name FROM category" },
   {
    "name": "Subcategory",
    "query": "SELECT s.name FROM subcategory s JOIN category c ON c.id = s.category_id WHERE c.name IN (${Category})"
   }
  ]
 },
 "panels": [
  {
   "title": "Spends by category",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%m/%Y') AS 'Month/Year',\n  category_name AS 'Category',\n  SUM(value) AS 'Total'\n FROM (\n  SELECT\n    s.date,\n    sc.name AS category_name,\n    CASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n    JOIN category sc ON sc.id = s.category_id\n    WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n    GROUP BY s.id ) s\n GROUP BY s.category_name, DATE_FORMAT(s.date, '%m/%Y')\n ORDER BY DATE_FORMAT(s.date, '%m/%Y') ASC, s.category_name ASC\n"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  SUM(value) AS 'Total'\nFROM (\n  SELECT\n    CASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n    JOIN category sc ON sc.id = s.category_id\n    WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n    GROUP BY s.id ) s"
    }
   ]
  },
  {
   "title": "Spends by subcategory",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%m/%Y') AS 'Month/Year',\n  subcategory_name AS 'Subcategory',\n  SUM(value) AS 'Total'\n FROM (\n  SELECT\n    s.date,\n    ss.name AS subcategory_name,\n    CASE\n      WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n    JOIN category sc ON s.category_id = sc.id\n    WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n    GROUP BY s.id ) s\n GROUP BY s.subcategory_name, DATE_FORMAT(s.date, '%m/%Y')\n ORDER BY DATE_FORMAT(s.date, '%m/%Y') ASC, s.subcategory_name ASC\n"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  SUM(value) AS 'Total'\nFROM (\n  SELECT\n    CASE\n      WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value)\n      ELSE AVG(s.value)\n    END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n    JOIN category sc ON s.category_id = sc.id\n    WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n    GROUP BY s.id ) s"
    }
   ]
  },
  {
   "title": "Spends by group",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%m/%Y') AS 'Month/Year',\n  group_name AS 'Group',\n  SUM(value) AS 'Total'\n FROM (\n  SELECT\n    s.date,\n    sg.name AS group_name,\n    CASE\n      WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value)\n      ELSE AVG(s.value)\n    END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON s.subcategory_id = ss.id\n    LEFT JOIN `group` sg ON s.group_id = sg.id\n    JOIN category sc ON s.category_id = sc.id\n    WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n    GROUP BY s.id ) s\n GROUP BY s.group_name, DATE_FORMAT(s.date, '%m/%Y')\n ORDER BY DATE_FORMAT(s.date, '%m/%Y') ASC, s.group_name ASC\n"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  SUM(value) AS 'Total'\nFROM (\n  SELECT\n    CASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value)\n    END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON s.subcategory_id = ss.id\n    JOIN category sc ON s.category_id = sc.id\n    WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n    GROUP BY s.id ) s"
    }
   ]
  },
  {
   "title": "Spends by category",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  DATE_FORMAT(s.date, '%m/%Y') AS 'Month/Year',\n  SUM(CASE WHEN s.category_id = 1 THEN s.value ELSE 0 END) AS 'Services',\n  SUM(CASE WHEN s.category_id = 2 THEN s.value ELSE 0 END) AS 'Health',\n  SUM(CASE WHEN s.category_id = 3 THEN s.value ELSE 0 END) AS 'Entertainment'\n FROM (\n  SELECT\n    s.date,\n    s.category_id,\n    CASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON ss.id = s.subcategory_id\n    JOIN category sc ON sc.id = s.category_id\n    WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n    GROUP BY s.id) s\n GROUP BY DATE_FORMAT(s.date, '%m/%Y')\n"
    }
   ]
  },
  {
   "title": "Spends by subcategory (using SUM-CASE)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  DATE_FORMAT(s.date, '%m/%Y') AS 'Month/Year',\n  SUM(CASE WHEN s.subcategory_id = 1 THEN s.value ELSE 0 END) AS 'Basic',\n  SUM(CASE WHEN s.subcategory_id = 2 THEN s.value ELSE 0 END) AS 'Internet',\n  SUM(CASE WHEN s.subcategory_id = 3 THEN s.value ELSE 0 END) AS 'Medicine',\n  SUM(CASE WHEN s.subcategory_id IS NULL THEN s.value ELSE 0 END) AS 'Sin definir'\n FROM (\n  SELECT\n    s.date,\n    s.subcategory_id,\n    CASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON s.subcategory_id = ss.id\n    JOIN category sc ON s.category_id = sc.id\n    WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\n    GROUP BY s.id) s\n GROUP BY DATE_FORMAT(s.date, '%m/%Y')"
    }
   ]
  },
  {
   "title": "Spends by subcategory",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  $__timeGroupAlias(date,'1M'),\n  ss.name,\n  SUM(s.value) AS ''\nFROM spend s\nLEFT JOIN subcategory ss ON s.subcategory_id = ss.id\nJOIN category sc ON s.category_id = sc.id\nWHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory}))\nGROUP BY 1, ss.id\nORDER BY 1\n\n/*asdas */"
    }
   ]
  },
  {
   "title": "Spends by group",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  DATE_FORMAT(s.date, '%m/%Y') AS 'Month/Year',\n  SUM(CASE WHEN s.group_id = 1 THEN s.value ELSE 0 END) AS 'Gas',\n  SUM(CASE WHEN s.group_id = 2 THEN s.value ELSE 0 END) AS 'Electricity',\n  SUM(CASE WHEN s.group_id IS NULL THEN s.value ELSE 0 END) AS 'Sin definir'\n FROM (\n  SELECT\n    s.date,\n    s.group_id,\n    CASE WHEN i.value IS NOT NULL THEN AVG(s.value) - SUM(i.value) ELSE AVG(s.value) END AS value\n    FROM spend s\n    LEFT JOIN income i ON s.id = i.spend_id\n    LEFT JOIN subcategory ss ON s.subcategory_id = ss.id\n    LEFT JOIN `group` sg ON s.group_id = sg.id\n    JOIN category sc ON s.category_id = sc.id\n    WHERE $__timeFilter(s.date) AND sc.name IN (${Category}) AND (s.subcategory_id IS NULL OR ss.name IN (${Subcategory})) \n    GROUP BY s.id) s\n GROUP BY DATE_FORMAT(s.date, '%m/%Y')\n"
    }
   ]
  }
 ]
}