package com.bruno.misgastos.enums;

public enum ErrorCode {
  INTERNAL_SERVER_ERROR,
  BAD_REQUEST,
  REST_CLIENT_EXCEPTION,
  RESOURCE_NOT_FOUND,
  UNAUTHORIZED,
  ENCRYPTION_ERROR,
  GOOGLE_API_ERROR,
  GOOGLE_AUTH_ERROR,
  INVALID_TASK_CONFIG
}
