spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - https://www.googleapis.com/auth/tasks.readonly
        provider:
          google:
            issuer-uri: https://accounts.google.com # OpenID Connect (OIDC) provider
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
mis-gastos:
  security:
    authorized-google-accounts: ${MIS_GASTOS_GOOGLE_ACCOUNTS}
    admin:
      client-id: ${MIS_GASTOS_ADMIN_JWT_CLIENT_ID}
      client-secret: ${MIS_GASTOS_ADMIN_JWT_CLIENT_SECRET}
    jwt:
      ttl-in-hours: 1
    google:
      task-list-id: ${MIS_GASTOS_GOOGLE_TASK_LIST_ID}