{
 "title": "Mis gastos - Spends vs Income",
 "time": { "from": "2025-12-22T06:21:26.000Z", "to": "2026-01-30T00:18:28.000Z" },
 "templating": {
  "list": [
   { "name": "Account", "label": "Account", "query": "SELECT a.name FROM account a" }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; align-items: center;\">\n  <h1 style=\"margin: 0;\">Spends vs Income</h1>\n</div>"
   }
  },
  {
   "title": " Spends",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  SUM(s.value) AS 'value'\nFROM spend s\nINNER JOIN account aa ON aa.id = s.account_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\n "
    }
   ]
  },
  {
   "title": " Income",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  SUM(i.value) AS 'value'\nFROM income i\nINNER JOIN account aa ON aa.id = i.account_id\nWHERE\n  $__timeFilter(i.date)\n  AND aa.name IN (${Account})\n "
    }
   ]
  },
  {
   "title": "Percentage saved",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "(($B - $A)/$B)*100", "type": "math" }
   ]
  },
  {
   "title": "Spends by account",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  SUM(s.value) AS value,\n  aa.name AS metric\nFROM spend s\nJOIN account aa ON aa.id = s.account_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\nGROUP BY aa.name"
    }
   ]
  },
  {
   "title": "Spends by account",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  DATE_FORMAT(s.date, '%Y-%m') AS 'Month',\n  aa.name AS 'Name',\n  SUM(s.value) AS 'Amount'\nFROM spend s\nJOIN account aa ON aa.id = s.account_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\nGROUP BY 1, aa.name\nORDER BY 1, aa.name"
    }
   ]
  },
  {
   "title": "Spends vs Income",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  $__timeGroupAlias(s.date, '1M'),\n  SUM(s.value) AS 'Spends'\nFROM spend s\nJOIN account aa ON aa.id = s.account_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\nGROUP BY 1, name\nORDER BY 1, name"
    },
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  $__timeGroupAlias(i.date, '1M'),\n  SUM(i.value) AS 'Income'\nFROM income i \nJOIN account aa ON aa.id = i.account_id\nWHERE\n    $__timeFilter(i.date)\n    AND aa.name IN (${Account})\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Percentage saved",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "targets": [
    { "expression": "(($B -$A)/$B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Incomes",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  DATE_FORMAT(i.date, \"%Y-%m-%d\") AS 'Date',\n  it.name AS 'Income type',\n  i.description AS 'Description',\n  i.value AS 'Amount'\nFROM income i\nINNER JOIN income_type it ON i.income_type_id = it.id\nINNER JOIN account aa ON aa.id = i.account_id\nLEFT JOIN spend s ON i.spend_id = s.id\nWHERE\n  $__timeFilter(i.date)\n  AND aa.name IN (${Account})\nORDER BY 1"
    }
   ]
  }
 ]
}