{
 "title": "Mis gastos (monthly) V2",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Account", "label": "Account", "query": "SELECT a.name FROM account a" },
   { "name": "Category", "query": "SELECT name FROM category" },
   {
    "name": "Subcategory",
    "query": "SELECT s.name FROM subcategory s JOIN category c ON c.id = s.category_id WHERE c.name IN (${Category})"
   },
   {
    "name": "Group",
    "label": "Group",
    "query": "SELECT g.name FROM `group` g JOIN subcategory s ON s.id = g.subcategory_id WHERE s.name IN (${Subcategory})"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; align-items: center;\">\n  <h1 style=\"margin: 0;\">Monthly dashboard</h1>\n</div>"
   }
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 0 },
   "options": {
    "content": "- Reimbursements are recorded on the same date as the original spend. For example, if you spend $10 in category A on 01/01/2026 and later receive a $1 reimbursement on 01/02/2026, that $1 will be reflected in **January**, not February."
   }
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  SUM(s.value - COALESCE(i.total_income, 0)) AS 'value'\nFROM spend s\nLEFT JOIN (\n  SELECT\n    spend_id,\n    SUM(value) AS total_income\n  FROM income\n  GROUP BY spend_id\n) i ON s.id = i.spend_id\nJOIN account aa ON aa.id = s.account_id\nJOIN category cc ON cc.id = s.category_id\nLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\nLEFT JOIN `group` gg ON gg.id = s.group_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\n  AND cc.name IN (${Category})\n  AND (\n    s.subcategory_id IS NULL\n    OR '${Subcategory:regex}' IN ('', '()')\n    OR (\n      ss.name REGEXP '^(${Subcategory:regex})$'\n      AND (\n        s.group_id IS NULL\n        OR '${Group:regex}' IN ('', '()') \n        OR gg.name REGEXP '^(${Group:regex})$'\n      )\n    )\n  )"
    }
   ]
  },
  {
   "title": "Spends by account",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  SUM(s.value - COALESCE(i.total_income, 0)) AS value,\n  aa.name AS metric\nFROM spend s\nLEFT JOIN (\n  SELECT\n    spend_id,\n    SUM(value) AS total_income\n  FROM income\n  GROUP BY spend_id\n) i ON s.id = i.spend_id\nJOIN account aa ON aa.id = s.account_id\nJOIN category cc ON cc.id = s.category_id\nLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\nLEFT JOIN `group` gg ON gg.id = s.group_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\n  AND cc.name IN (${Category})\n  AND (\n    s.subcategory_id IS NULL\n    OR '${Subcategory:regex}' IN ('', '()')\n    OR (\n      ss.name REGEXP '^(${Subcategory:regex})$'\n      AND (\n        s.group_id IS NULL\n        OR '${Group:regex}' IN ('', '()') \n        OR gg.name REGEXP '^(${Group:regex})$'\n      )\n    )\n  )\nGROUP BY aa.name"
    }
   ]
  },
  {
   "title": "Spends by account",
   "type": "table",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 7 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  DATE_FORMAT(s.date, '%Y-%m') AS 'Month',\n  aa.name AS 'Name',\n  SUM(s.value - COALESCE(i.total_income, 0)) AS 'Amount'\nFROM spend s\nLEFT JOIN (\n  SELECT\n    spend_id,\n    SUM(value) AS total_income\n  FROM income\n  GROUP BY spend_id\n) i ON s.id = i.spend_id\nJOIN account aa ON aa.id = s.account_id\nJOIN category cc ON cc.id = s.category_id\nLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\nLEFT JOIN `group` gg ON gg.id = s.group_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\n  AND cc.name IN (${Category})\n  AND (\n    s.subcategory_id IS NULL\n    OR '${Subcategory:regex}' IN ('', '()')\n    OR (\n      ss.name REGEXP '^(${Subcategory:regex})$'\n      AND (\n        s.group_id IS NULL\n        OR '${Group:regex}' IN ('', '()') \n        OR gg.name REGEXP '^(${Group:regex})$'\n      )\n    )\n  )\nGROUP BY 1, aa.name\nORDER BY 1, aa.name"
    }
   ]
  },
  {
   "title": "Spends by category",
   "type": "table",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  DATE_FORMAT(s.date, '%Y-%m') AS 'Month',\n  cc.name AS 'Name',\n  SUM(s.value - COALESCE(i.total_income, 0)) AS 'Amount'\nFROM spend s\nLEFT JOIN (\n  SELECT\n    spend_id,\n    SUM(value) AS total_income\n  FROM income\n  GROUP BY spend_id\n) i ON s.id = i.spend_id\nJOIN account aa ON aa.id = s.account_id\nJOIN category cc ON cc.id = s.category_id\nLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\nLEFT JOIN `group` gg ON gg.id = s.group_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\n  AND cc.name IN (${Category})\n  AND (\n    s.subcategory_id IS NULL\n    OR '${Subcategory:regex}' IN ('', '()')\n    OR (\n      ss.name REGEXP '^(${Subcategory:regex})$'\n      AND (\n        s.group_id IS NULL\n        OR '${Group:regex}' IN ('', '()') \n        OR gg.name REGEXP '^(${Group:regex})$'\n      )\n    )\n  )\nGROUP BY 1, cc.name\nORDER BY 1, cc.name"
    }
   ]
  },
  {
   "title": "Spends by subcategory",
   "type": "table",
   "gridPos": { "h": 20, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  DATE_FORMAT(s.date, '%Y-%m') AS 'Month',\n  COALESCE(ss.name, 'No subcategory') AS 'Name',\n  SUM(s.value - COALESCE(i.total_income, 0)) AS 'Amount'\nFROM spend s\nLEFT JOIN (\n  SELECT\n    spend_id,\n    SUM(value) AS total_income\n  FROM income\n  GROUP BY spend_id\n) i ON s.id = i.spend_id\nJOIN account aa ON aa.id = s.account_id\nJOIN category cc ON cc.id = s.category_id\nLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\nLEFT JOIN `group` gg ON gg.id = s.group_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\n  AND cc.name IN (${Category})\n  AND (\n    s.subcategory_id IS NULL\n    OR '${Subcategory:regex}' IN ('', '()')\n    OR (\n      ss.name REGEXP '^(${Subcategory:regex})$'\n      AND (\n        s.group_id IS NULL\n        OR '${Group:regex}' IN ('', '()') \n        OR gg.name REGEXP '^(${Group:regex})$'\n      )\n    )\n  )\nGROUP BY 1, COALESCE(ss.name, 'No subcategory')\nORDER BY 1, COALESCE(ss.name, 'No subcategory')"
    }
   ]
  },
  {
   "title": "Spends by group",
   "type": "table",
   "gridPos": { "h": 20, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  DATE_FORMAT(s.date, '%Y-%m') AS 'Month',\n  COALESCE(gg.name, 'No group') AS 'Name',\n  SUM(s.value - COALESCE(i.total_income, 0)) AS 'Amount'\nFROM spend s\nLEFT JOIN (\n  SELECT\n    spend_id,\n    SUM(value) AS total_income\n  FROM income\n  GROUP BY spend_id\n) i ON s.id = i.spend_id\nJOIN account aa ON aa.id = s.account_id\nJOIN category cc ON cc.id = s.category_id\nLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\nLEFT JOIN `group` gg ON gg.id = s.group_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\n  AND cc.name IN (${Category})\n  AND (\n    s.subcategory_id IS NULL\n    OR '${Subcategory:regex}' IN ('', '()')\n    OR (\n      ss.name REGEXP '^(${Subcategory:regex})$'\n      AND (\n        s.group_id IS NULL\n        OR '${Group:regex}' IN ('', '()') \n        OR gg.name REGEXP '^(${Group:regex})$'\n      )\n    )\n  )\nGROUP BY 1, COALESCE(gg.name, 'No group') \nORDER BY 1, COALESCE(gg.name, 'No group')"
    }
   ]
  },
  {
   "title": "Spends by category",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  SUM(s.value - COALESCE(i.total_income, 0)) AS value,\n  cc.name AS metric\nFROM spend s\nLEFT JOIN (\n  SELECT\n    spend_id,\n    SUM(value) AS total_income\n  FROM income\n  GROUP BY spend_id\n) i ON s.id = i.spend_id\nJOIN account aa ON aa.id = s.account_id\nJOIN category cc ON cc.id = s.category_id\nLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\nLEFT JOIN `group` gg ON gg.id = s.group_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\n  AND cc.name IN (${Category})\n  AND (\n    s.subcategory_id IS NULL\n    OR '${Subcategory:regex}' IN ('', '()')\n    OR (\n      ss.name REGEXP '^(${Subcategory:regex})$'\n      AND (\n        s.group_id IS NULL\n        OR '${Group:regex}' IN ('', '()') \n        OR gg.name REGEXP '^(${Group:regex})$'\n      )\n    )\n  )\nGROUP BY cc.name"
    }
   ]
  },
  {
   "title": "Spends by category",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 41 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  $__timeGroupAlias(s.date, '1M'),\n  cc.name AS name,\n  SUM(s.value - COALESCE(i.total_income, 0)) AS ''\nFROM spend s\nLEFT JOIN (\n  SELECT\n    spend_id,\n    SUM(value) AS total_income\n  FROM income\n  GROUP BY spend_id\n) i ON s.id = i.spend_id\nJOIN account aa ON aa.id = s.account_id\nJOIN category cc ON cc.id = s.category_id\nLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\nLEFT JOIN `group` gg ON gg.id = s.group_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\n  AND cc.name IN (${Category})\n  AND (\n    s.subcategory_id IS NULL\n    OR '${Subcategory:regex}' IN ('', '()')\n    OR (\n      ss.name REGEXP '^(${Subcategory:regex})$'\n      AND (\n        s.group_id IS NULL\n        OR '${Group:regex}' IN ('', '()') \n        OR gg.name REGEXP '^(${Group:regex})$'\n      )\n    )\n  )\nGROUP BY 1, cc.name\nORDER BY 1, cc.name"
    }
   ]
  },
  {
   "title": "Spends by subcategory",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  SUM(s.value - COALESCE(i.total_income, 0)) AS value,\n  COALESCE(ss.name, 'No subcategory') AS metric\nFROM spend s\nLEFT JOIN (\n  SELECT\n    spend_id,\n    SUM(value) AS total_income\n  FROM income\n  GROUP BY spend_id\n) i ON s.id = i.spend_id\nJOIN account aa ON aa.id = s.account_id\nJOIN category cc ON cc.id = s.category_id\nLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\nLEFT JOIN `group` gg ON gg.id = s.group_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\n  AND cc.name IN (${Category})\n  AND (\n    s.subcategory_id IS NULL\n    OR '${Subcategory:regex}' IN ('', '()')\n    OR (\n      ss.name REGEXP '^(${Subcategory:regex})$'\n      AND (\n        s.group_id IS NULL\n        OR '${Group:regex}' IN ('', '()') \n        OR gg.name REGEXP '^(${Group:regex})$'\n      )\n    )\n  )\nGROUP BY COALESCE(ss.name, 'No subcategory')"
    }
   ]
  },
  {
   "title": "Spends by subcategory",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 53 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  $__timeGroupAlias(s.date, '1M'),\n  COALESCE(ss.name, 'No subcategory'),\n  SUM(s.value - COALESCE(i.total_income, 0))  AS ''\nFROM spend s\nLEFT JOIN (\n  SELECT\n    spend_id,\n    SUM(value) AS total_income\n  FROM income\n  GROUP BY spend_id\n) i ON s.id = i.spend_id\nJOIN account aa ON aa.id = s.account_id\nJOIN category cc ON cc.id = s.category_id\nLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\nLEFT JOIN `group` gg ON gg.id = s.group_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\n  AND cc.name IN (${Category})\n  AND (\n    s.subcategory_id IS NULL\n    OR '${Subcategory:regex}' IN ('', '()')\n    OR (\n      ss.name REGEXP '^(${Subcategory:regex})$'\n      AND (\n        s.group_id IS NULL\n        OR '${Group:regex}' IN ('', '()') \n        OR gg.name REGEXP '^(${Group:regex})$'\n      )\n    )\n  )\nGROUP BY 1, COALESCE(ss.name, 'No subcategory')\nORDER BY 1, COALESCE(ss.name, 'No subcategory')"
    }
   ]
  },
  {
   "title": "Spends by group",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  SUM(s.value - COALESCE(i.total_income, 0)) AS value,\n  COALESCE(gg.name, 'No group') AS metric\nFROM spend s\nLEFT JOIN (\n  SELECT\n    spend_id,\n    SUM(value) AS total_income\n  FROM income\n  GROUP BY spend_id\n) i ON s.id = i.spend_id\nJOIN account aa ON aa.id = s.account_id\nJOIN category cc ON cc.id = s.category_id\nLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\nLEFT JOIN `group` gg ON gg.id = s.group_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\n  AND cc.name IN (${Category})\n  AND (\n    s.subcategory_id IS NULL\n    OR '${Subcategory:regex}' IN ('', '()')\n    OR (\n      ss.name REGEXP '^(${Subcategory:regex})$'\n      AND (\n        s.group_id IS NULL\n        OR '${Group:regex}' IN ('', '()') \n        OR gg.name REGEXP '^(${Group:regex})$'\n      )\n    )\n  )\nGROUP BY COALESCE(gg.name, 'No group')"
    }
   ]
  },
  {
   "title": "Spends by group",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 65 },
   "targets": [
    {
     "dataset": "misgastos",
     "rawSql": "SELECT\n  $__timeGroupAlias(s.date, '1M'),\n  COALESCE(gg.name, 'No group'),\n  SUM(s.value - COALESCE(i.total_income, 0)) AS ''\nFROM spend s\nLEFT JOIN (\n  SELECT\n    spend_id,\n    SUM(value) AS total_income\n  FROM income\n  GROUP BY spend_id\n) i ON s.id = i.spend_id\nJOIN account aa ON aa.id = s.account_id\nJOIN category cc ON cc.id = s.category_id\nLEFT JOIN subcategory ss ON ss.id = s.subcategory_id\nLEFT JOIN `group` gg ON gg.id = s.group_id\nWHERE\n  $__timeFilter(s.date)\n  AND aa.name IN (${Account})\n  AND cc.name IN (${Category})\n  AND (\n    s.subcategory_id IS NULL\n    OR '${Subcategory:regex}' IN ('', '()')\n    OR (\n      ss.name REGEXP '^(${Subcategory:regex})$'\n      AND (\n        s.group_id IS NULL\n        OR '${Group:regex}' IN ('', '()') \n        OR gg.name REGEXP '^(${Group:regex})$'\n      )\n    )\n  )\nGROUP BY 1, COALESCE(gg.name, 'No group')\nORDER BY 1, COALESCE(gg.name, 'No group')"
    }
   ]
  }
 ]
}